#!/usr/bin/env python3
"""
Pressure System Model (PSM) Simulation
--------------------------------------
Runs a simplified weekly simulation of the Pressure System Model (PSM)
using default parameters or those loaded from parameters.json.
Generates placeholder figures and prints summary statistics.
"""

import numpy as np
import json
import csv
import matplotlib.pyplot as plt
import os


# ---------------------------------------------------------------------
# Load parameters (fallback to defaults if parameters.json not found)
# ---------------------------------------------------------------------
try:
    with open("parameters.json", "r") as f:
        params = json.load(f)
except FileNotFoundError:
    print("parameters.json not found - using example defaults")
    params = {
        "tanks": ["US", "China", "Canada", "EU", "LatAm", "Other"],
        "initial_P": [29.15, 19.28, 2.25, 19.45, 7.12, 70.8],
        "C": [0.023, 0.045, 0.008, 0.012, 0.022, 0.03],
        "L": [0.03, 0.016, 0.0338, 0.032, 0.0764, 0.052],
        "K": [
            [0, 0.03, 0.02, 0.02, 0.015, 0.01],
            [0.03, 0, 0.01, 0.015, 0.01, 0.005],
            [0.02, 0.01, 0, 0.015, 0.01, 0.005],
            [0.02, 0.015, 0.015, 0, 0.01, 0.01],
            [0.015, 0.01, 0.01, 0.01, 0, 0.005],
            [0.01, 0.005, 0.005, 0.01, 0.005, 0],
        ],
        "R_baseline": [[1.0] * 6 for _ in range(6)],
    }

tanks = params["tanks"]
P0 = np.array(params["initial_P"])
C = np.array(params["C"])
L = np.array(params["L"])
K = np.array(params["K"])
R = np.array(params["R_baseline"])

# ---------------------------------------------------------------------
# PSM dynamics
# ---------------------------------------------------------------------
def psm_dynamics(P, C, L, K, R, stochastic=False, leak_sigma=0.005, flow_sigma=0.01):
    """Compute weekly change dP/dt for each tank."""
    n = len(P)
    flows = np.zeros(n)
    for i in range(n):
        for j in range(n):
            if i != j:
                flows[i] -= K[i][j] * R[i][j] * (P[i] - P[j]) / 52  # weekly scale
    dPdt = (C * P / 52) - (L * P) + flows
    if stochastic:
        noise_leak = np.random.normal(0, leak_sigma * P)
        noise_flow = np.random.normal(0, flow_sigma * np.abs(flows))
        dPdt += noise_leak + noise_flow
    return dPdt


def run_sim(
    P0, weeks=1, C=None, L=None, K=None, R=None, stochastic=False, num_runs=1, dt=1 / 52
):
    """Run the simulation with explicit Euler integration (fast and stable)."""
    n = len(P0)
    results = []

    for r in range(num_runs):
        P = P0.copy()
        for _ in range(weeks):
            dPdt = psm_dynamics(P, C, L, K, R, stochastic)
            P += dPdt * dt
        results.append(P)

    results = np.array(results)
    mean = np.mean(results, axis=0)
    std = np.std(results, axis=0)
    return mean, std


# ---------------------------------------------------------------------
# Example: 1-week ensemble simulation
# ---------------------------------------------------------------------
mean, std = run_sim(P0, weeks=1, C=C, L=L, K=K, R=R, stochastic=True, num_runs=100)
print("Mean:", mean)
print("Std:", std)


# ---------------------------------------------------------------------
# Note: Figures are generated by run_full_validation.py from actual data
# This script provides quick simulation results only
# ---------------------------------------------------------------------
print("\nNote: To generate validation figures, run: python3 run_full_validation.py")
print("      Figures in psm_paper/ are generated from actual simulation data, not placeholders.")


# ---------------------------------------------------------------------
# Load and preview sample CSV data (for diagnostics)
# ---------------------------------------------------------------------
if os.path.exists("sample_data.csv"):
    with open("sample_data.csv", "r") as f:
        reader = csv.reader(f)
        data = list(reader)
    print("Sample data loaded:")
    for row in data:
        print(row)
else:
    print("sample_data.csv not found (skipping preview)")

